<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PackageId>MailDirector</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FlightMail.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="YamlDotNet" Version="17.1.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Graph" Version="5.62.0" />
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
  </ItemGroup>

</Project>
